# encoding: UTF-8

include Vorax
include Parser

describe 'package_spec' do

	it 'should get the vim format' do
    text = File.open("spec/sql/muci.spc", 'rb') { |file| file.read }
    parser = Vorax::Parser::Declare.new(text)
		parser.to_vim.should == %q[[ {'name' : "MY_CONSTANT1", 'is_a' : "constant", 'type' : "varchar2", 'captured_text' : "MY_CONSTANT1 constant varchar2(100) := 'abc';"},{'name' : "MY_CONSTANT2", 'is_a' : "constant", 'type' : "integer", 'captured_text' : "MY_CONSTANT2 constant integer := 10;"},{'name' : "ex_no_data_found", 'is_a' : "exception", 'type' : "exception", 'captured_text' : "ex_no_data_found exception;"},{'name' : "ex_custom", 'is_a' : "exception", 'type' : "exception", 'captured_text' : "ex_custom exception;"},{'name' : "my_cursor", 'is_a' : "cursor", 'type' : "", 'captured_text' : "cursor my_cursor is\n    select * from user_tables;"},{'name' : "population_type", 'is_a' : "type", 'type' : "table", 'captured_text' : "type population_type is table of varchar2(100);"},{'name' : "g_var1", 'is_a' : "variable", 'type' : "integer", 'captured_text' : "g_var1 integer;"},{'name' : "g_var2", 'is_a' : "variable", 'type' : "varchar2", 'captured_text' : "g_var2 varchar2(100) := 'xyz';"},{'name' : "g_var3", 'is_a' : "variable", 'type' : "dual.dummy%type", 'captured_text' : "g_var3 dual.dummy%type;"},{'name' : "g_var4", 'is_a' : "variable", 'type' : "all_objects%rowtype", 'captured_text' : "g_var4 all_objects%rowtype;"},{'name' : "my_proc", 'is_a' : "procedure", 'type' : "", 'captured_text' : "procedure my_proc(p1 integer);"},{'name' : "my_func", 'is_a' : "function", 'type' : "", 'captured_text' : "function my_func(param1 varchar2, param2 boolean := true) return boolean;"} ]]
	end

  it 'should work with a simple package' do
    text = File.open("spec/sql/muci.spc", 'rb') { |file| file.read }
    parser = Vorax::Parser::Declare.new(text)
		parser.items.length.should == 12
		parser.items.include?(DeclareItem.new("MY_CONSTANT1",
																					:constant,
																					"varchar2",
																					"MY_CONSTANT1 constant varchar2(100) := 'abc';")).should be_true
		parser.items.include?(DeclareItem.new("MY_CONSTANT2",
																					:constant,
																					"integer",
																					"MY_CONSTANT2 constant integer := 10;")).should be_true
		parser.items.include?(DeclareItem.new("ex_no_data_found",
																					:exception,
																					"exception",
																					"ex_no_data_found exception;")).should be_true
		parser.items.include?(DeclareItem.new("ex_custom",
																					:exception,
																					"exception",
																					"ex_custom exception;")).should be_true
		parser.items.include?(DeclareItem.new("my_cursor",
																					:cursor,
																					nil,
																					"cursor my_cursor is\n    select * from user_tables;")).should be_true
		parser.items.include?(DeclareItem.new("population_type",
																					:type,
																					"table",
																					"type population_type is table of varchar2(100);")).should be_true
		parser.items.include?(DeclareItem.new("g_var1",
																					:variable,
																					"integer",
																					"g_var1 integer;")).should be_true
		parser.items.include?(DeclareItem.new("g_var2",
																					:variable,
																					"varchar2",
																					"g_var2 varchar2(100) := 'xyz';")).should be_true
		parser.items.include?(DeclareItem.new("g_var3",
																					:variable,
																					"dual.dummy%type",
																					"g_var3 dual.dummy%type;")).should be_true
		parser.items.include?(DeclareItem.new("g_var4",
																					:variable,
																					"all_objects%rowtype",
																					"g_var4 all_objects%rowtype;")).should be_true
		parser.items.include?(DeclareItem.new("my_proc",
																					:procedure,
																					nil,
																					"procedure my_proc(p1 integer);")).should be_true
		parser.items.include?(DeclareItem.new("my_func",
																					:function,
																					nil,
																					"function my_func(param1 varchar2, param2 boolean := true) return boolean;")).should be_true
  end

  it 'should work with a big package spec' do
    text = File.open('spec/sql/dbms_stats.spc', 'rb') { |file| file.read }
    parser = Vorax::Parser::Declare.new(text)
		parser.items.include?(DeclareItem.new("numarray", :type, "varray", "type numarray is varray(256) of number;")).should be_true
		parser.items.include?(DeclareItem.new("datearray", :type, "varray", "type datearray is varray(256) of date;")).should be_true
		parser.items.include?(DeclareItem.new("chararray", :type, "varray", "type chararray is varray(256) of varchar2(4000);")).should be_true
		parser.items.include?(DeclareItem.new("rawarray", :type, "varray", "type rawarray is varray(256) of raw(2000);")).should be_true
		parser.items.include?(DeclareItem.new("fltarray", :type, "varray", "type fltarray is varray(256) of binary_float;")).should be_true
		parser.items.include?(DeclareItem.new("dblarray", :type, "varray", "type dblarray is varray(256) of binary_double;")).should be_true
		parser.items.include?(DeclareItem.new("StatRec", :type, "record", "type StatRec is record (\r\n  epc    number,\r\n  minval raw(2000),\r\n  maxval raw(2000),\r\n  bkvals numarray,\r\n  novals numarray,\r\n  chvals chararray,\r\n  eavs   number);")).should be_true
		parser.items.include?(DeclareItem.new("ObjectElem", :type, "record", "type ObjectElem is record (\r\n  ownname     varchar2(32),        objtype     varchar2(6),         objname     varchar2(32),        partname    varchar2(32),        subpartname varchar2(32)       );")).should be_true
		parser.items.include?(DeclareItem.new("ObjectTab", :type, "table", "type ObjectTab is table of ObjectElem;")).should be_true
		parser.items.include?(DeclareItem.new("DiffRepElem", :type, "record", "type DiffRepElem is record (\r\n  report     clob,                 maxdiffpct number);")).should be_true
		parser.items.include?(DeclareItem.new("DiffRepTab", :type, "table", "type DiffRepTab is table of DiffRepElem;")).should be_true
		parser.items.include?(DeclareItem.new("CContext", :type, "varray", "type CContext is varray(10) of varchar2(100);")).should be_true
		parser.items.include?(DeclareItem.new("AUTO_CASCADE", :constant, "BOOLEAN", "AUTO_CASCADE CONSTANT BOOLEAN := null;")).should be_true
		parser.items.include?(DeclareItem.new("AUTO_INVALIDATE", :constant, "BOOLEAN", "AUTO_INVALIDATE CONSTANT BOOLEAN := null;")).should be_true
		parser.items.include?(DeclareItem.new("AUTO_SAMPLE_SIZE", :constant, "NUMBER", "AUTO_SAMPLE_SIZE        CONSTANT NUMBER := 0;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_DEGREE", :constant, "NUMBER", "DEFAULT_DEGREE          CONSTANT NUMBER := 32767;")).should be_true
		parser.items.include?(DeclareItem.new("AUTO_DEGREE", :constant, "NUMBER", "AUTO_DEGREE             CONSTANT NUMBER := 32768;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_CASCADE", :constant, "BOOLEAN", "DEFAULT_CASCADE          CONSTANT BOOLEAN  := null;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_DEGREE_VALUE", :constant, "NUMBER", "DEFAULT_DEGREE_VALUE     CONSTANT NUMBER   := 32766;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_ESTIMATE_PERCENT", :constant, "NUMBER", "DEFAULT_ESTIMATE_PERCENT CONSTANT NUMBER   := 101;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_METHOD_OPT", :constant, "VARCHAR2", "DEFAULT_METHOD_OPT       CONSTANT VARCHAR2(1) := 'Z';")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_NO_INVALIDATE", :constant, "BOOLEAN", "DEFAULT_NO_INVALIDATE    CONSTANT BOOLEAN     := null;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_GRANULARITY", :constant, "VARCHAR2", "DEFAULT_GRANULARITY      CONSTANT VARCHAR2(1) := 'Z';")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_PUBLISH", :constant, "BOOLEAN", "DEFAULT_PUBLISH          CONSTANT BOOLEAN     := true;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_INCREMENTAL", :constant, "BOOLEAN", "DEFAULT_INCREMENTAL      CONSTANT BOOLEAN     := false;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_STALE_PERCENT", :constant, "NUMBER", "DEFAULT_STALE_PERCENT    CONSTANT NUMBER      := 10;")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_AUTOSTATS_TARGET", :constant, "VARCHAR2", "DEFAULT_AUTOSTATS_TARGET CONSTANT VARCHAR2(1) := 'Z';")).should be_true
		parser.items.include?(DeclareItem.new("DEFAULT_STAT_CATEGORY", :constant, "VARCHAR2", "DEFAULT_STAT_CATEGORY    CONSTANT VARCHAR2(20) := 'OBJECT_STATS';")).should be_true
		parser.items.include?(DeclareItem.new("PURGE_ALL", :constant, "TIMESTAMP", "PURGE_ALL CONSTANT TIMESTAMP WITH TIME ZONE :=\r\n TO_TIMESTAMP_TZ('1001-01-0101:00:00-00:00','YYYY-MM-DDHH:MI:SSTZH:TZM');")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values", :procedure, nil, "procedure prepare_column_values(\r\n        srec in out StatRec, charvals chararray);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values", :procedure, nil, "procedure prepare_column_values(\r\n        srec in out StatRec, datevals datearray);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values", :procedure, nil, "procedure prepare_column_values(\r\n        srec in out StatRec, numvals numarray);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values", :procedure, nil, "procedure prepare_column_values(\r\n        srec in out StatRec, fltvals fltarray);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values", :procedure, nil, "procedure prepare_column_values(\r\n        srec in out StatRec, dblvals dblarray);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values", :procedure, nil, "procedure prepare_column_values(\r\n        srec in out StatRec, rawvals rawarray);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values_nvarchar", :procedure, nil, "procedure prepare_column_values_nvarchar(\r\n        srec in out StatRec, nvmin nvarchar2, nvmax nvarchar2);")).should be_true
		parser.items.include?(DeclareItem.new("prepare_column_values_rowid", :procedure, nil, "procedure prepare_column_values_rowid(\r\n        srec in out StatRec, rwmin rowid, rwmax rowid);")).should be_true
		parser.items.include?(DeclareItem.new("set_param", :procedure, nil, "procedure set_param(\r\n    pname in varchar2,\r\n    pval  in varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("get_param", :function, nil, "function get_param(\r\n    pname   in varchar2)\r\n  return varchar2;")).should be_true
		parser.items.include?(DeclareItem.new("reset_param_defaults", :procedure, nil, "procedure reset_param_defaults;")).should be_true
		parser.items.include?(DeclareItem.new("reset_global_pref_defaults", :procedure, nil, "procedure reset_global_pref_defaults;")).should be_true
		parser.items.include?(DeclareItem.new("set_global_prefs", :procedure, nil, "procedure set_global_prefs(\r\n    pname   varchar2,\r\n    pvalue  varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("get_prefs", :function, nil, "function get_prefs(\r\n    pname   in varchar2,\r\n    ownname in varchar2 default null,\r\n    tabname in varchar2 default null)\r\n  return varchar2;")).should be_true
		parser.items.include?(DeclareItem.new("set_table_prefs", :procedure, nil, "procedure set_table_prefs(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    pname   varchar2,\r\n    pvalue  varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("delete_table_prefs", :procedure, nil, "procedure delete_table_prefs(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    pname   varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("export_table_prefs", :procedure, nil, "procedure export_table_prefs(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("import_table_prefs", :procedure, nil, "procedure import_table_prefs(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("set_schema_prefs", :procedure, nil, "procedure set_schema_prefs(\r\n    ownname varchar2,\r\n    pname   varchar2,\r\n    pvalue  varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("delete_schema_prefs", :procedure, nil, "procedure delete_schema_prefs(\r\n    ownname varchar2,\r\n    pname   varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("export_schema_prefs", :procedure, nil, "procedure export_schema_prefs(\r\n    ownname varchar2,\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("import_schema_prefs", :procedure, nil, "procedure import_schema_prefs(\r\n    ownname varchar2,\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("set_database_prefs", :procedure, nil, "procedure set_database_prefs(\r\n    pname   varchar2,\r\n    pvalue  varchar2,\r\n    add_sys boolean default false);")).should be_true
		parser.items.include?(DeclareItem.new("delete_database_prefs", :procedure, nil, "procedure delete_database_prefs(\r\n    pname   varchar2,\r\n    add_sys boolean default false);")).should be_true
		parser.items.include?(DeclareItem.new("export_database_prefs", :procedure, nil, "procedure export_database_prefs(\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default null,\r\n    add_sys boolean  default false);")).should be_true
		parser.items.include?(DeclareItem.new("import_database_prefs", :procedure, nil, "procedure import_database_prefs(\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default null,\r\n    add_sys boolean  default false);")).should be_true
		parser.items.include?(DeclareItem.new("to_cascade_type", :function, nil, "function to_cascade_type(cascade varchar2) return boolean;")).should be_true
		parser.items.include?(DeclareItem.new("to_estimate_percent_type", :function, nil, "function to_estimate_percent_type(estimate_percent varchar2) return number;")).should be_true
		parser.items.include?(DeclareItem.new("to_degree_type", :function, nil, "function to_degree_type(degree varchar2) return number;")).should be_true
		parser.items.include?(DeclareItem.new("to_no_invalidate_type", :function, nil, "function to_no_invalidate_type(no_invalidate varchar2) return boolean;")).should be_true
		parser.items.include?(DeclareItem.new("to_publish_type", :function, nil, "function to_publish_type(publish varchar2) return boolean;")).should be_true
		parser.items.include?(DeclareItem.new("init_package", :procedure, nil, "procedure init_package;")).should be_true
		parser.items.include?(DeclareItem.new("publish_pending_stats", :procedure, nil, "procedure publish_pending_stats(\r\n    ownname varchar2 default USER,\r\n    tabname varchar2,\r\n    no_invalidate boolean default\r\n      to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n    force   boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("export_pending_stats", :procedure, nil, "procedure export_pending_stats(\r\n    ownname varchar2 default USER,\r\n    tabname varchar2,\r\n    stattab varchar2,\r\n    statid  varchar2 default null,\r\n    statown varchar2 default USER);")).should be_true
		parser.items.include?(DeclareItem.new("delete_pending_stats", :procedure, nil, "procedure delete_pending_stats(\r\n    ownname varchar2 default USER,\r\n    tabname varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("resume_gather_stats", :procedure, nil, "procedure resume_gather_stats;")).should be_true
		parser.items.include?(DeclareItem.new("set_column_stats", :procedure, nil, "procedure set_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        distcnt number default null, density number default null,\r\n        nullcnt number default null, srec StatRec default null,\r\n        avgclen number default null, flags number default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("set_column_stats", :procedure, nil, "procedure set_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        ext_stats raw,\r\n        stattypown varchar2 default null,\r\n        stattypname varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("set_index_stats", :procedure, nil, "procedure set_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        numrows number default null, numlblks number default null,\r\n        numdist number default null, avglblk number default null,\r\n        avgdblk number default null, clstfct number default null,\r\n        indlevel number default null, flags number default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        guessq number default null,\r\n        cachedblk number default null,\r\n        cachehit number default null,\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("set_index_stats", :procedure, nil, "procedure set_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        ext_stats raw,\r\n        stattypown varchar2 default null,\r\n        stattypname varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("set_table_stats", :procedure, nil, "procedure set_table_stats(\r\n        ownname varchar2,\r\n        tabname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null,\r\n        statid varchar2 default null,\r\n        numrows number default null,\r\n        numblks number default null,\r\n        avgrlen number default null,\r\n        flags number default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        cachedblk number default null,\r\n        cachehit number default null,\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value", :procedure, nil, "procedure convert_raw_value(\r\n        rawval raw, resval out varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value", :procedure, nil, "procedure convert_raw_value(\r\n        rawval raw, resval out date);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value", :procedure, nil, "procedure convert_raw_value(\r\n        rawval raw, resval out number);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value", :procedure, nil, "procedure convert_raw_value(\r\n        rawval raw, resval out binary_float);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value", :procedure, nil, "procedure convert_raw_value(\r\n        rawval raw, resval out binary_double);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value_nvarchar", :procedure, nil, "procedure convert_raw_value_nvarchar(\r\n        rawval raw, resval out nvarchar2);")).should be_true
		parser.items.include?(DeclareItem.new("convert_raw_value_rowid", :procedure, nil, "procedure convert_raw_value_rowid(\r\n        rawval raw, resval out rowid);")).should be_true
		parser.items.include?(DeclareItem.new("get_column_stats", :procedure, nil, "procedure get_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        distcnt out number, density out number,\r\n        nullcnt out number, srec out StatRec,\r\n        avgclen out number,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("get_column_stats", :procedure, nil, "procedure get_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        ext_stats out raw,\r\n        stattypown out varchar2, stattypname out varchar2,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("get_index_stats", :procedure, nil, "procedure get_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        numrows out number, numlblks out number,\r\n        numdist out number, avglblk out number,\r\n        avgdblk out number, clstfct out number,\r\n        indlevel out number,\r\n        statown varchar2 default null,\r\n        guessq out number,\r\n        cachedblk out number,\r\n        cachehit out number);")).should be_true
		parser.items.include?(DeclareItem.new("get_index_stats", :procedure, nil, "procedure get_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        numrows out number, numlblks out number,\r\n        numdist out number, avglblk out number,\r\n        avgdblk out number, clstfct out number,\r\n        indlevel out number,\r\n        statown varchar2 default null,\r\n        guessq out number);")).should be_true
		parser.items.include?(DeclareItem.new("get_index_stats", :procedure, nil, "procedure get_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        numrows out number, numlblks out number,\r\n        numdist out number, avglblk out number,\r\n        avgdblk out number, clstfct out number,\r\n        indlevel out number,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("get_index_stats", :procedure, nil, "procedure get_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        ext_stats out raw,\r\n        stattypown out varchar2, stattypname out varchar2,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("get_table_stats", :procedure, nil, "procedure get_table_stats(\r\n        ownname varchar2, tabname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        numrows out number, numblks out number,\r\n        avgrlen out number,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("get_table_stats", :procedure, nil, "procedure get_table_stats(\r\n        ownname varchar2,\r\n        tabname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null,\r\n        statid varchar2 default null,\r\n        numrows out number,\r\n        numblks out number,\r\n        avgrlen out number,\r\n        statown varchar2 default null,\r\n        cachedblk out number,\r\n        cachehit out number);")).should be_true
		parser.items.include?(DeclareItem.new("delete_column_stats", :procedure, nil, "procedure delete_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        cascade_parts boolean default true,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE,\r\n        col_stat_type varchar2 default 'ALL');")).should be_true
		parser.items.include?(DeclareItem.new("delete_index_stats", :procedure, nil, "procedure delete_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        cascade_parts boolean default true,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        stattype varchar2 default 'ALL',\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("delete_table_stats", :procedure, nil, "procedure delete_table_stats(\r\n        ownname varchar2, tabname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        cascade_parts boolean default true,\r\n        cascade_columns boolean default true,\r\n        cascade_indexes boolean default true,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        stattype varchar2 default 'ALL',\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("delete_schema_stats", :procedure, nil, "procedure delete_schema_stats(\r\n        ownname varchar2,\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        stattype varchar2 default 'ALL',\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("delete_database_stats", :procedure, nil, "procedure delete_database_stats(\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        stattype varchar2 default 'ALL',\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("create_stat_table", :procedure, nil, "procedure create_stat_table(\r\n        ownname varchar2, stattab varchar2,\r\n        tblspace varchar2 default null,\r\n        global_temporary boolean default false);")).should be_true
		parser.items.include?(DeclareItem.new("drop_stat_table", :procedure, nil, "procedure drop_stat_table(\r\n        ownname varchar2, stattab varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("upgrade_stat_table", :procedure, nil, "procedure upgrade_stat_table(\r\n        ownname varchar2, stattab varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("export_column_stats", :procedure, nil, "procedure export_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("export_index_stats", :procedure, nil, "procedure export_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("export_table_stats", :procedure, nil, "procedure export_table_stats(\r\n        ownname varchar2, tabname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2, statid varchar2 default null,\r\n        cascade boolean default true,\r\n        statown varchar2 default null,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY\r\n);")).should be_true
		parser.items.include?(DeclareItem.new("export_schema_stats", :procedure, nil, "procedure export_schema_stats(\r\n        ownname varchar2,\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY);")).should be_true
		parser.items.include?(DeclareItem.new("export_database_stats", :procedure, nil, "procedure export_database_stats(\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY);")).should be_true
		parser.items.include?(DeclareItem.new("import_column_stats", :procedure, nil, "procedure import_column_stats(\r\n        ownname varchar2, tabname varchar2, colname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("import_index_stats", :procedure, nil, "procedure import_index_stats(\r\n        ownname varchar2, indname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("import_table_stats", :procedure, nil, "procedure import_table_stats(\r\n        ownname varchar2, tabname varchar2,\r\n        partname varchar2 default null,\r\n        stattab varchar2, statid varchar2 default null,\r\n        cascade boolean default true,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY);")).should be_true
		parser.items.include?(DeclareItem.new("import_schema_stats", :procedure, nil, "procedure import_schema_stats(\r\n        ownname varchar2,\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY);")).should be_true
		parser.items.include?(DeclareItem.new("import_database_stats", :procedure, nil, "procedure import_database_stats(\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY\r\n        );")).should be_true
		parser.items.include?(DeclareItem.new("gather_index_stats", :procedure, nil, "procedure gather_index_stats\r\n    (ownname varchar2, indname varchar2, partname varchar2 default null,\r\n     estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     statown varchar2 default null,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     stattype varchar2 default 'DATA',\r\n     force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("gather_table_stats", :procedure, nil, "procedure gather_table_stats\r\n    (ownname varchar2, tabname varchar2, partname varchar2 default null,\r\n     estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default  DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     statown varchar2 default null,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     stattype varchar2 default 'DATA',\r\n     force boolean default FALSE,\r\n           context dbms_stats.CContext default null);")).should be_true
		parser.items.include?(DeclareItem.new("gather_schema_stats", :procedure, nil, "procedure gather_schema_stats\r\n    (ownname varchar2,\r\n     estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default  DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     options varchar2 default 'GATHER', objlist out ObjectTab,\r\n     statown varchar2 default null,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     gather_temp boolean default FALSE,\r\n     gather_fixed boolean default FALSE,\r\n     stattype varchar2 default 'DATA',\r\n     force boolean default FALSE,\r\n     obj_filter_list ObjectTab default null);")).should be_true
		parser.items.include?(DeclareItem.new("gather_schema_stats", :procedure, nil, "procedure gather_schema_stats\r\n    (ownname varchar2,\r\n     estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     options varchar2 default 'GATHER', statown varchar2 default null,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     gather_temp boolean default FALSE,\r\n     gather_fixed boolean default FALSE,\r\n     stattype varchar2 default 'DATA',\r\n     force boolean default FALSE,\r\n     obj_filter_list ObjectTab default null);")).should be_true
		parser.items.include?(DeclareItem.new("gather_database_stats", :procedure, nil, "procedure gather_database_stats\r\n    (estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     options varchar2 default 'GATHER', objlist out ObjectTab,\r\n     statown varchar2 default null,\r\n     gather_sys boolean default TRUE,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     gather_temp boolean default FALSE,\r\n     gather_fixed boolean default FALSE,\r\n     stattype varchar2 default 'DATA',\r\n     obj_filter_list ObjectTab default null);")).should be_true
		parser.items.include?(DeclareItem.new("gather_database_stats", :procedure, nil, "procedure gather_database_stats\r\n    (estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     options varchar2 default 'GATHER', statown varchar2 default null,\r\n     gather_sys boolean default TRUE,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     gather_temp boolean default FALSE,\r\n     gather_fixed boolean default FALSE,\r\n     stattype varchar2 default 'DATA',\r\n     obj_filter_list ObjectTab default null);")).should be_true
		parser.items.include?(DeclareItem.new("generate_stats", :procedure, nil, "procedure generate_stats\r\n    (ownname varchar2, objname varchar2,\r\n     organized number default 7,\r\n     force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("flush_database_monitoring_info", :procedure, nil, "procedure flush_database_monitoring_info;")).should be_true
		parser.items.include?(DeclareItem.new("alter_schema_tab_monitoring", :procedure, nil, "procedure alter_schema_tab_monitoring\r\n  (ownname varchar2 default NULL, monitoring boolean default TRUE);")).should be_true
		parser.items.include?(DeclareItem.new("alter_database_tab_monitoring", :procedure, nil, "procedure alter_database_tab_monitoring\r\n  (monitoring boolean default TRUE, sysobjs boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("gather_system_stats", :procedure, nil, "procedure gather_system_stats (\r\n  gathering_mode  varchar2 default 'NOWORKLOAD',\r\n  interval  integer  default 60,\r\n  stattab   varchar2 default null,\r\n  statid    varchar2 default null,\r\n  statown   varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("get_system_stats", :procedure, nil, "procedure get_system_stats (\r\n   status     out   varchar2,\r\n   dstart     out   date,\r\n   dstop      out   date,\r\n   pname            varchar2,\r\n   pvalue     out   number,\r\n   stattab          varchar2 default null,\r\n   statid           varchar2 default null,\r\n   statown          varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("set_system_stats", :procedure, nil, "procedure set_system_stats (\r\n   pname            varchar2,\r\n   pvalue           number,\r\n   stattab          varchar2 default null,\r\n   statid           varchar2 default null,\r\n   statown          varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("delete_system_stats", :procedure, nil, "procedure delete_system_stats (\r\n   stattab         varchar2  default nulL,\r\n   statid          varchar2  default nulL,\r\n   statown         varchar2  default null);")).should be_true
		parser.items.include?(DeclareItem.new("import_system_stats", :procedure, nil, "procedure import_system_stats (\r\n   stattab  varchar2,\r\n   statid   varchar2 default null,\r\n   statown  varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("export_system_stats", :procedure, nil, "procedure export_system_stats (\r\n   stattab  varchar2,\r\n   statid   varchar2 default null,\r\n   statown  varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("gather_fixed_objects_stats", :procedure, nil, "procedure gather_fixed_objects_stats\r\n    (stattab varchar2 default null, statid varchar2 default null,\r\n     statown varchar2 default null,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')));")).should be_true
		parser.items.include?(DeclareItem.new("delete_fixed_objects_stats", :procedure, nil, "procedure delete_fixed_objects_stats(\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n        to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("export_fixed_objects_stats", :procedure, nil, "procedure export_fixed_objects_stats(\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null);")).should be_true
		parser.items.include?(DeclareItem.new("import_fixed_objects_stats", :procedure, nil, "procedure import_fixed_objects_stats(\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n           to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("gather_dictionary_stats", :procedure, nil, "procedure gather_dictionary_stats\r\n    (comp_id varchar2 default null,\r\n     estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     options varchar2 default 'GATHER AUTO', objlist out ObjectTab,\r\n     statown varchar2 default null,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     stattype varchar2 default 'DATA',\r\n     obj_filter_list ObjectTab default null);")).should be_true
		parser.items.include?(DeclareItem.new("gather_dictionary_stats", :procedure, nil, "procedure gather_dictionary_stats\r\n    (comp_id varchar2 default null,\r\n     estimate_percent number default DEFAULT_ESTIMATE_PERCENT,\r\n     block_sample boolean default FALSE,\r\n     method_opt varchar2 default DEFAULT_METHOD_OPT,\r\n     degree number default to_degree_type(get_param('DEGREE')),\r\n     granularity varchar2 default DEFAULT_GRANULARITY,\r\n     cascade boolean default DEFAULT_CASCADE,\r\n     stattab varchar2 default null, statid varchar2 default null,\r\n     options varchar2 default 'GATHER AUTO', statown varchar2 default null,\r\n     no_invalidate boolean default\r\n       to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n     stattype varchar2 default 'DATA',\r\n     obj_filter_list ObjectTab default null);")).should be_true
		parser.items.include?(DeclareItem.new("delete_dictionary_stats", :procedure, nil, "procedure delete_dictionary_stats(\r\n        stattab varchar2 default null, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        stattype varchar2 default 'ALL',\r\n        force boolean default FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("export_dictionary_stats", :procedure, nil, "procedure export_dictionary_stats(\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY);")).should be_true
		parser.items.include?(DeclareItem.new("import_dictionary_stats", :procedure, nil, "procedure import_dictionary_stats(\r\n        stattab varchar2, statid varchar2 default null,\r\n        statown varchar2 default null,\r\n        no_invalidate boolean default\r\n          to_no_invalidate_type(get_param('NO_INVALIDATE')),\r\n        force boolean default FALSE,\r\n        stat_category varchar2 default DEFAULT_STAT_CATEGORY);")).should be_true
		parser.items.include?(DeclareItem.new("lock_table_stats", :procedure, nil, "procedure lock_table_stats(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    stattype varchar2 default 'ALL');")).should be_true
		parser.items.include?(DeclareItem.new("lock_partition_stats", :procedure, nil, "procedure lock_partition_stats(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    partname varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("lock_schema_stats", :procedure, nil, "procedure lock_schema_stats(\r\n    ownname varchar2,\r\n    stattype varchar2 default 'ALL');")).should be_true
		parser.items.include?(DeclareItem.new("unlock_table_stats", :procedure, nil, "procedure unlock_table_stats(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    stattype varchar2 default 'ALL');")).should be_true
		parser.items.include?(DeclareItem.new("unlock_partition_stats", :procedure, nil, "procedure unlock_partition_stats(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    partname varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("unlock_schema_stats", :procedure, nil, "procedure unlock_schema_stats(\r\n    ownname varchar2,\r\n    stattype varchar2 default 'ALL');")).should be_true
		parser.items.include?(DeclareItem.new("restore_table_stats", :procedure, nil, "procedure restore_table_stats(\r\n    ownname varchar2,\r\n    tabname varchar2,\r\n    as_of_timestamp timestamp with time zone,\r\n    restore_cluster_index boolean default FALSE,\r\n    force boolean default FALSE,\r\n    no_invalidate boolean default\r\n      to_no_invalidate_type(get_param('NO_INVALIDATE')));")).should be_true
		parser.items.include?(DeclareItem.new("restore_schema_stats", :procedure, nil, "procedure restore_schema_stats(\r\n    ownname varchar2,\r\n    as_of_timestamp timestamp with time zone,\r\n    force boolean default FALSE,\r\n    no_invalidate boolean default\r\n      to_no_invalidate_type(get_param('NO_INVALIDATE')));")).should be_true
		parser.items.include?(DeclareItem.new("restore_database_stats", :procedure, nil, "procedure restore_database_stats(\r\n    as_of_timestamp timestamp with time zone,\r\n    force boolean default FALSE,\r\n    no_invalidate boolean default\r\n      to_no_invalidate_type(get_param('NO_INVALIDATE')));")).should be_true
		parser.items.include?(DeclareItem.new("restore_fixed_objects_stats", :procedure, nil, "procedure restore_fixed_objects_stats(\r\n    as_of_timestamp timestamp with time zone,\r\n    force boolean default FALSE,\r\n    no_invalidate boolean default\r\n      to_no_invalidate_type(get_param('NO_INVALIDATE')));")).should be_true
		parser.items.include?(DeclareItem.new("restore_dictionary_stats", :procedure, nil, "procedure restore_dictionary_stats(\r\n    as_of_timestamp timestamp with time zone,\r\n    force boolean default FALSE,\r\n    no_invalidate boolean default\r\n      to_no_invalidate_type(get_param('NO_INVALIDATE')));")).should be_true
		parser.items.include?(DeclareItem.new("restore_system_stats", :procedure, nil, "procedure restore_system_stats(\r\n    as_of_timestamp timestamp with time zone);")).should be_true
		parser.items.include?(DeclareItem.new("purge_stats", :procedure, nil, "procedure purge_stats(\r\n    before_timestamp timestamp with time zone);")).should be_true
		parser.items.include?(DeclareItem.new("alter_stats_history_retention", :procedure, nil, "procedure alter_stats_history_retention(\r\n    retention in number);")).should be_true
		parser.items.include?(DeclareItem.new("get_stats_history_retention", :function, nil, "function get_stats_history_retention return number;")).should be_true
		parser.items.include?(DeclareItem.new("get_stats_history_availability", :function, nil, "function get_stats_history_availability\r\n             return timestamp with time zone;")).should be_true
		parser.items.include?(DeclareItem.new("copy_table_stats", :procedure, nil, "procedure copy_table_stats(\r\n        ownname varchar2,\r\n        tabname varchar2,\r\n        srcpartname varchar2,\r\n        dstpartname varchar2,\r\n        scale_factor number DEFAULT 1,\r\n        flags number DEFAULT null,\r\n        force boolean DEFAULT FALSE);")).should be_true
		parser.items.include?(DeclareItem.new("diff_table_stats_in_stattab", :function, nil, "function diff_table_stats_in_stattab(\r\n      ownname      varchar2,\r\n      tabname      varchar2,\r\n      stattab1     varchar2,\r\n      stattab2     varchar2 default null,\r\n      pctthreshold number   default 10,\r\n      statid1      varchar2 default null,\r\n      statid2      varchar2 default null,\r\n      stattab1own  varchar2 default null,\r\n      stattab2own  varchar2 default null)\r\n   return DiffRepTab pipelined;")).should be_true
		parser.items.include?(DeclareItem.new("diff_table_stats_in_history", :function, nil, "function diff_table_stats_in_history(\r\n      ownname      varchar2,\r\n      tabname      varchar2,\r\n      time1        timestamp with time zone,\r\n      time2        timestamp with time zone default null,\r\n      pctthreshold number   default 10)\r\n    return DiffRepTab pipelined;")).should be_true
		parser.items.include?(DeclareItem.new("diff_table_stats_in_pending", :function, nil, "function diff_table_stats_in_pending(\r\n      ownname      varchar2,\r\n      tabname      varchar2,\r\n      time_stamp   timestamp with time zone default null,\r\n      pctthreshold number   default 10)\r\n    return DiffRepTab pipelined;")).should be_true
		parser.items.include?(DeclareItem.new("create_extended_stats", :function, nil, "function create_extended_stats(\r\n      ownname    varchar2,\r\n      tabname    varchar2,\r\n      extension  varchar2)\r\n    return varchar2;")).should be_true
		parser.items.include?(DeclareItem.new("create_extended_stats", :function, nil, "function create_extended_stats(\r\n      ownname    varchar2,\r\n      tabname    varchar2)\r\n    return clob;")).should be_true
		parser.items.include?(DeclareItem.new("show_extended_stats_name", :function, nil, "function show_extended_stats_name(\r\n      ownname    varchar2,\r\n      tabname    varchar2,\r\n      extension  varchar2)\r\n    return varchar2;")).should be_true
		parser.items.include?(DeclareItem.new("drop_extended_stats", :procedure, nil, "procedure drop_extended_stats(\r\n      ownname    varchar2,\r\n      tabname    varchar2,\r\n      extension  varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("merge_col_usage", :procedure, nil, "procedure merge_col_usage(\r\n      dblink varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("seed_col_usage", :procedure, nil, "procedure seed_col_usage(\r\n      sqlset_name IN         VARCHAR2,\r\n      owner_name  IN         VARCHAR2,\r\n      time_limit  IN         POSITIVE DEFAULT NULL);")).should be_true
		parser.items.include?(DeclareItem.new("reset_col_usage", :procedure, nil, "procedure reset_col_usage(\r\n      ownname      varchar2,\r\n      tabname      varchar2);")).should be_true
		parser.items.include?(DeclareItem.new("report_col_usage", :function, nil, "function report_col_usage(\r\n      ownname      varchar2,\r\n      tabname      varchar2)  return clob;")).should be_true
		parser.items.include?(DeclareItem.new("gather_database_stats_job_proc", :procedure, nil, "procedure gather_database_stats_job_proc;")).should be_true
		parser.items.include?(DeclareItem.new("cleanup_stats_job_proc", :procedure, nil, "procedure cleanup_stats_job_proc(\r\n      ctx number, job_owner varchar2, job_name varchar2,\r\n      sesid number, sesser number);")).should be_true
  end

  it 'should work with a SYS package spec' do
    text = File.open('spec/sql/dbms_crypto.spc', 'rb') { |file| file.read }
    parser = Vorax::Parser::Declare.new(text)
		DeclareItem.new("HASH_MD4", :constant, "PLS_INTEGER", "HASH_MD4           CONSTANT PLS_INTEGER            :=     1;")
		DeclareItem.new("HASH_MD5", :constant, "PLS_INTEGER", "HASH_MD5           CONSTANT PLS_INTEGER            :=     2;")
		DeclareItem.new("HASH_SH1", :constant, "PLS_INTEGER", "HASH_SH1           CONSTANT PLS_INTEGER            :=     3;")
		DeclareItem.new("HMAC_MD5", :constant, "PLS_INTEGER", "HMAC_MD5           CONSTANT PLS_INTEGER            :=     1;")
		DeclareItem.new("HMAC_SH1", :constant, "PLS_INTEGER", "HMAC_SH1           CONSTANT PLS_INTEGER            :=     2;")
		DeclareItem.new("ENCRYPT_DES", :constant, "PLS_INTEGER", "ENCRYPT_DES        CONSTANT PLS_INTEGER            :=     1;")
		DeclareItem.new("ENCRYPT_3DES_2KEY", :constant, "PLS_INTEGER", "ENCRYPT_3DES_2KEY  CONSTANT PLS_INTEGER            :=     2;")
		DeclareItem.new("ENCRYPT_3DES", :constant, "PLS_INTEGER", "ENCRYPT_3DES       CONSTANT PLS_INTEGER            :=     3;")
		DeclareItem.new("ENCRYPT_AES", :constant, "PLS_INTEGER", "ENCRYPT_AES        CONSTANT PLS_INTEGER            :=     4;")
		DeclareItem.new("ENCRYPT_PBE_MD5DES", :constant, "PLS_INTEGER", "ENCRYPT_PBE_MD5DES CONSTANT PLS_INTEGER            :=     5;")
		DeclareItem.new("ENCRYPT_AES128", :constant, "PLS_INTEGER", "ENCRYPT_AES128     CONSTANT PLS_INTEGER            :=     6;")
		DeclareItem.new("ENCRYPT_AES192", :constant, "PLS_INTEGER", "ENCRYPT_AES192     CONSTANT PLS_INTEGER            :=     7;")
		DeclareItem.new("ENCRYPT_AES256", :constant, "PLS_INTEGER", "ENCRYPT_AES256     CONSTANT PLS_INTEGER            :=     8;")
		DeclareItem.new("CHAIN_CBC", :constant, "PLS_INTEGER", "CHAIN_CBC          CONSTANT PLS_INTEGER            :=   256;")
		DeclareItem.new("CHAIN_CFB", :constant, "PLS_INTEGER", "CHAIN_CFB          CONSTANT PLS_INTEGER            :=   512;")
		DeclareItem.new("CHAIN_ECB", :constant, "PLS_INTEGER", "CHAIN_ECB          CONSTANT PLS_INTEGER            :=   768;")
		DeclareItem.new("CHAIN_OFB", :constant, "PLS_INTEGER", "CHAIN_OFB          CONSTANT PLS_INTEGER            :=  1024;")
		DeclareItem.new("PAD_PKCS5", :constant, "PLS_INTEGER", "PAD_PKCS5          CONSTANT PLS_INTEGER            :=  4096;")
		DeclareItem.new("PAD_NONE", :constant, "PLS_INTEGER", "PAD_NONE           CONSTANT PLS_INTEGER            :=  8192;")
		DeclareItem.new("PAD_ZERO", :constant, "PLS_INTEGER", "PAD_ZERO           CONSTANT PLS_INTEGER            := 12288;")
		DeclareItem.new("PAD_ORCL", :constant, "PLS_INTEGER", "PAD_ORCL           CONSTANT PLS_INTEGER            := 16384;")
		DeclareItem.new("ENCRYPT_RC4", :constant, "PLS_INTEGER", "ENCRYPT_RC4        CONSTANT PLS_INTEGER            :=   129;")
		DeclareItem.new("DES_CBC_PKCS5", :constant, "PLS_INTEGER", "DES_CBC_PKCS5      CONSTANT PLS_INTEGER            := ENCRYPT_DES\r\n                                                          + CHAIN_CBC\r\n                                                          + PAD_PKCS5;")
		DeclareItem.new("DES3_CBC_PKCS5", :constant, "PLS_INTEGER", "DES3_CBC_PKCS5     CONSTANT PLS_INTEGER            := ENCRYPT_3DES\r\n                                                          + CHAIN_CBC\r\n                                                          + PAD_PKCS5;")
		DeclareItem.new("AES_CBC_PKCS5", :constant, "PLS_INTEGER", "AES_CBC_PKCS5      CONSTANT PLS_INTEGER            := ENCRYPT_AES\r\n                                                          + CHAIN_CBC\r\n                                                          + PAD_PKCS5;")
		DeclareItem.new("CipherSuiteInvalid", :exception, "EXCEPTION", "CipherSuiteInvalid EXCEPTION;")
		DeclareItem.new("CipherSuiteNull", :exception, "EXCEPTION", "CipherSuiteNull EXCEPTION;")
		DeclareItem.new("KeyNull", :exception, "EXCEPTION", "KeyNull EXCEPTION;")
		DeclareItem.new("KeyBadSize", :exception, "EXCEPTION", "KeyBadSize EXCEPTION;")
		DeclareItem.new("DoubleEncryption", :exception, "EXCEPTION", "DoubleEncryption EXCEPTION;")
		DeclareItem.new("Encrypt", :function, nil, "FUNCTION  Encrypt (src IN            RAW,\r\n                       typ IN            PLS_INTEGER,\r\n                       key IN            RAW,\r\n                       iv  IN            RAW          DEFAULT NULL)\r\n      RETURN RAW;")
		DeclareItem.new("Encrypt", :procedure, nil, "PROCEDURE Encrypt (dst IN OUT NOCOPY BLOB,\r\n                       src IN            BLOB,\r\n                       typ IN            PLS_INTEGER,\r\n                       key IN            RAW,\r\n                       iv  IN            RAW          DEFAULT NULL);")
		DeclareItem.new("Encrypt", :procedure, nil, "PROCEDURE Encrypt (dst IN OUT NOCOPY BLOB,\r\n                       src IN            CLOB         CHARACTER SET ANY_CS,\r\n                       typ IN            PLS_INTEGER,\r\n                       key IN            RAW,\r\n                       iv  IN            RAW          DEFAULT NULL);")
		DeclareItem.new("Decrypt", :function, nil, "FUNCTION  Decrypt (src IN            RAW,\r\n                       typ IN            PLS_INTEGER,\r\n                       key IN            RAW,\r\n                       iv  IN            RAW          DEFAULT NULL)\r\n       RETURN RAW;")
		DeclareItem.new("Decrypt", :procedure, nil, "PROCEDURE Decrypt (dst IN OUT NOCOPY BLOB,\r\n                       src IN            BLOB,\r\n                       typ IN            PLS_INTEGER,\r\n                       key IN            RAW,\r\n                       iv  IN            RAW          DEFAULT NULL);")
		DeclareItem.new("Decrypt", :procedure, nil, "PROCEDURE Decrypt (dst IN OUT NOCOPY CLOB         CHARACTER SET ANY_CS,\r\n                       src IN            BLOB,\r\n                       typ IN            PLS_INTEGER,\r\n                       key IN            RAW,\r\n                       iv  IN            RAW          DEFAULT NULL);")
		DeclareItem.new("Hash", :function, nil, "FUNCTION Hash (src IN RAW,\r\n                   typ IN PLS_INTEGER)\r\n      RETURN RAW DETERMINISTIC;")
		DeclareItem.new("Hash", :function, nil, "FUNCTION Hash (src IN BLOB,\r\n                   typ IN PLS_INTEGER)\r\n      RETURN RAW DETERMINISTIC;")
		DeclareItem.new("Hash", :function, nil, "FUNCTION Hash (src IN CLOB        CHARACTER SET ANY_CS,\r\n                   typ IN PLS_INTEGER)\r\n      RETURN RAW DETERMINISTIC;")
		DeclareItem.new("Mac", :function, nil, "FUNCTION Mac (src IN RAW,\r\n                  typ IN PLS_INTEGER,\r\n                  key IN RAW)\r\n      RETURN RAW;")
		DeclareItem.new("Mac", :function, nil, "FUNCTION Mac (src IN BLOB,\r\n                  typ IN PLS_INTEGER,\r\n                  key IN RAW)\r\n      RETURN RAW;")
		DeclareItem.new("Mac", :function, nil, "FUNCTION Mac (src IN CLOB         CHARACTER SET ANY_CS,\r\n                  typ IN PLS_INTEGER,\r\n                  key IN RAW)\r\n      RETURN RAW;")
		DeclareItem.new("RandomBytes", :function, nil, "FUNCTION RandomBytes (number_bytes IN PLS_INTEGER)\r\n      RETURN RAW;")
		DeclareItem.new("RandomNumber", :function, nil, "FUNCTION RandomNumber\r\n      RETURN NUMBER;")
		DeclareItem.new("RandomInteger", :function, nil, "FUNCTION RandomInteger\r\n      RETURN BINARY_INTEGER;")
  end

end
